required = ["github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"]

[[constraint]]
  name = "github.com/infobloxopen/atlas-app-toolkit"
  branch = "master"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.9.2"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.9"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/inflection"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.1"

[prune]
  go-tests = true
  unused-packages = true
